# 凡例 #################################
#
# 	id	 	= "種類.4桁の数字"
#	name	= "作品名"		# 改行は "<br>" を入れる
#	remark	= "コメント"	# 何を書いてもHTMLテーブルに出力されない
#	creator	= "作者名"		# 改行は "<br>" を入れる
#	nico	= "ニコニコID"	# 動画(sm～)、静画(im～)、立体(td～)
#	page	= "参照ページ"	# "[タイトル](URL)" 、または特殊形式 "bowlroll/番号" など

# T.xxxx = ツール ######################

[[item]]
id		= "T.0001"	# VRoid Studio
name	= "VRoid Studio"
remark	= "-"
creator	= "pixiv"
nico	= "-"
page	= "[VRoid Studio](https://vroid.com/studio)"

[[item]]
id		= "T.0002"	# Vroid2Pmx
name	= "Vroid2Pmx"
remark	= "-"
creator	= "miu"
nico	= "im10854785"
page	= "bowlroll/267190"

[[item]]
id		= "T.0003"	# PmxTailor
name	= "PmxTailor"
remark	= "-"
creator	= "miu"
nico	= "im10854784"
page	= "bowlroll/267191"

[[item]]
id		= "T.0004"	# VRM2PMXConverter
name	= "VRM2PMXConverter"
remark	= "-"
creator	= "superowner (原作)<br>winglayer (和訳)"
nico	= "sm34705374"
page	= "bowlroll/191067"

[[item]]
id		= "T.0005"	# BowlRoll
name	= "BowlRoll"
remark	= "-"
creator	= "BowlRoll アカウント"
nico	= "im4855495"
page	= "[BowlRoll について](https://bowlroll.net/about/index)"

[[item]]
id		= "T.0006"	# Ut Video Codec
name	= "Ut Video Codec"
remark	= "-"
creator	= "ゆーむP"
nico	= "im1922939"
page	= "[或るプログラマの一生](http://umezawa.dyndns.info/wordpress/?cat=28)"

[[item]]
id		= "T.0007"	# MikuMikuDance
name	= "MikuMikuDance"
remark	= "-"
creator	= "樋口優"
nico	= "sm2420025"
page	= "[VPVP](https://sites.google.com/view/vpvp/)"

[[item]]
id		= "T.0008"	# MikuMikuEffect
name	= "MikuMikuEffect"
remark	= "-"
creator	= "舞力介入P"
nico	= "sm12149815"
page	= "-"

[[item]]
id		= "T.0009"	# AviUtl
name	= "AviUtl"
remark	= "-"
creator	= "ＫＥＮくん"
nico	= "im1696493"
page	= "[AviUtlのお部屋](https://spring-fragrance.mints.ne.jp/aviutl/)"

[[item]]
id		= "T.0010"	# つんでれんこ
name	= "つんでれんこ"
remark	= "-"
creator	= "窓屋"
nico	= "sm7634361"
page	= "[つんでれんこ](https://tdenc.com/tdenc/)"

[[item]]
id		= "T.0011"	# PMXエディター
name	= "PMXエディター"
remark	= "-"
creator	= "極北P"
nico	= "sm20566765"
page	= "[とある工房](https://kkhk22.seesaa.net/category/14045227-1.html)"

[[item]]
id		= "T.0012"	# VMDサイジング
name	= "VMDサイジング"
remark	= "-"
creator	= "miu"
nico	= "im9755721"
page	= "bowlroll/197410"

[[item]]
id		= "T.0013"	# COEIROINK
name	= "COEIROINK"
remark	= "-"
creator	= "シロワニさん"
nico	= "sm39804441"
page	= "[COEIROINK](https://coeiroink.com/)"

[[item]]
id		= "T.0014"	# movie2avi.bat
name	= "movie2avi.bat"
remark	= "-"
creator	= "こ～りん"
nico	= "-"
page	= "bowlroll/10226"

[[item]]
id		= "T.0015"	# PictAcc
name	= "PictAcc"
remark	= "-"
creator	= "ファルコン"
nico	= "sm38345152"
page	= "bowlroll/248902"


# P.xxxx = プラグイン ##################

[[item]]
id		= "P.0001"	# 準標準ボーン追加
name	= "準標準ボーン追加<br>SemiStandardBones"
remark	= "-"
creator	= "そぼろ"
nico	= "sm14956092"
page	= "[MMD/PMDE_Plugins](https://onedrive.live.com/?id=EF581C37A4524EDA%21196&cid=EF581C37A4524EDA)"

[[item]]
id		= "P.0002"	# 闇鍋プラグイン
name	= "闇鍋プラグイン"
remark	= "-"
creator	= "t0r0"
nico	= "-"
page	= "bowlroll/9765"

[[item]]
id		= "P.0003"	# 捩りボーン自動分散
name	= "捩りボーン自動分散"
remark	= "-"
creator	= "P.I.P"
nico	= "-"
page	= "bowlroll/116180"

# 1.xxxx = モデル ######################

[[item]]
id	 	= "1.0001"	# ふっこ
name	= "ふっこ"
remark	= "-"
creator	= "BCD (--)"
nico	= "sm30453730"
page	= "x.com/BCD13342111/1400429706491555841"

[[item]]
id	 	= "1.0002"	# うに式 試1.66
name	= "うに式 試1.66"
remark	= "-"
creator	= "うに"
nico	= "sm33477899"
page	= "bowlroll/170989"

[[item]]
id      = "1.0003"	# VRoid A子
name	= "VRoid A子"
remark	= "-"
creator	= "yuima"
nico	= "td95636"
page	= "bowlroll/266800"

[[item]]
id	 	= "1.0004"	# VRoid F子
name	= "VRoid F子"
remark	= "-"
creator	= "yuima"
nico	= "td95636"
page	= "bowlroll/320277"

[[item]]
id	 	= "1.0005"	# VRoid B子
name	= "VRoid B子"
remark	= "-"
creator	= "yuima"
nico	= "td95636"
page	= "bowlroll/276667"

[[item]]
id	 	= "1.0006"	# VRoid C子
name	= "VRoid C子"
remark	= "-"
creator	= "yuima"
nico	= "td95636"
page	= "bowlroll/299133"

[[item]]
id	 	= "1.0007"	# VRoid D子
name	= "VRoid D子"
remark	= "-"
creator	= "yuima"
nico	= "td95636"
page	= "bowlroll/299134"

[[item]]
id	 	= "1.0008"	# 衣川希（おねーちゃん1号）
name	= "衣川希（おねーちゃん1号）"
remark	= "KEITEL式おねーちゃんズ"
creator	= "KEITEL"
nico	= "im10881555"
page	= "bowlroll/269833"

[[item]]
id	 	= "1.0009"	# 衣川光莉（おねーちゃん5号）
name	= "衣川光莉（おねーちゃん5号）"
remark	= "KEITEL式おねーちゃんズ"
creator	= "KEITEL"
nico	= "im10881555"
page	= "bowlroll/269833"


# 2.xxxx = ステージ ####################

[[item]]
id	 	= "2.0001"	# 絵画の洋館 廃墟版
name	= "絵画の洋館 廃墟版"
remark	= "-"
creator	= "NOB"
nico	= "im10674575"
page	= "[NOB's files](https://madaopnob.wixsite.com/files)"

[[item]]
id	 	= "2.0002"	# ムムム草原
name	= "草原"
remark	= "-"
creator	= "ムムム"
nico	= "im11255220"
page	= "bowlroll/305634"

[[item]]
id	 	= "2.0003"	# ストーンヘンジ
name	= "ストーンヘンジ"
remark	= "-"
creator	= "ばんぞく"
nico	= "im11156311"
page	= "bowlroll/297458"

[[item]]
id	 	= "2.0004"	# ウェスタンステージ
name	= "ウェスタンステージ"
remark	= "-"
creator	= "YOUCHA"
nico	= "sm27950318"
page	= "bowlroll/91070"

[[item]]
id	 	= "2.0005"	# ケロリン町2.0
name	= "ケロリン町2.0"
remark	= "-"
creator	= "kelorin jo (BTA)"
nico	= "sm15988891"
page	= "bowlroll/125407"

[[item]]
id	 	= "2.0006"	# レンガ壁の部屋-01
name	= "レンガ壁の部屋-01"
remark	= "-"
creator	= "ツチネコ"
nico	= "im6880180"
page	= "bowlroll/142449"

[[item]]
id	 	= "2.0007"	# 撮影用背景ステージ
name	= "撮影用背景ステージ"
remark	= "-"
creator	= "悟遠塔也"
nico	= "im5775513"
page	= "[悟が遠いロダ](http://ux.getuploader.com/Goto_Toya/download/30/撮影用背景2_v100.zip)"

[[item]]
id	 	= "2.0008"	# Kawaiiルーム
name	= "Kawaiiルーム"
remark	= "-"
creator	= "ムムム"
nico	= "im10756683"
page	= "bowlroll/255589"


# 3.xxxx = スカイドーム ################

[[item]]
id	 	= "3.0001"	# 桜の公園 NN8
name	= "桜の公園 NN8"
remark	= "-"
creator	= "怪獣対若大将P"
nico	= "im5653835"
page	= "bowlroll/97078"

[[item]]
id	 	= "3.0002"	# 天球Sunrise001
name	= "天球Sunrise001.x"
remark	= "お年始skyset.zip に含まれる"
creator	= "銀匙"
nico	= "im5653835"
page	= "[銀匙倉庫０１](https://ux.getuploader.com/silverspoon_01/download/14)"

# 4.xxxx = アクセサリ ##################

[[item]]
id	 	= "4.0001"	# コウモリパーティクル
name	= "コウモリパーティクル"
remark	= "-"
creator	= "山田淀子"
nico	= "sm39375203"
page	= "bowlroll/262776"

[[item]]
id	 	= "4.0002"	# ふかふか草むら
name	= "ふかふか草むら"
remark	= "-"
creator	= "ビームマンP"
nico	= "sm18156849"
page	= "[ビームマンのエフェクト置き場](https://w.atwiki.jp/beamman/)"

# 5.xxxx = エフェクト ##################

[[item]]
id	 	= "5.0001"	# AdultShader.fx
name	= "AdultShader.fx"
remark	= "-"
creator	= "Elle/データP"
nico	= "sm14067112"
page	= "[Elle/データPのデータポートⅡ](https://uu.getuploader.com/Elle_DataPort/download/9)"

[[item]]
id	 	= "5.0002"	# o_full-AlphaTest.fx
name	= "o_full-AlphaTest.fx"
remark	= "o_SurplusFilter に含まれる"
creator	= "おたもん"
nico	= "im3131306"
page	= "[MMD関連ファイル置き場](https://okoneya.jp/mmd_files/#o_SurplusFilter)"

[[item]]
id	 	= "5.0003"	# Color.fx
name	= "Color.fx"
remark	= "HariganeEffectUpdatePack20130711.zip に含まれる"
creator	= "針金P"
nico	= "sm14067112"
page	= "[針金のブログ](https://hariganep.seesaa.net/article/201203article_1.html)"

[[item]]
id	 	= "5.0004"	# KiraKira_Z
name	= "KiraKira_Z"
remark	= "-"
creator	= "ビームマンP"
nico	= "sm26425576"
page	= "[ビームマンのエフェクト置き場](https://w.atwiki.jp/beamman/)"

[[item]]
id	 	= "5.0005"	# SvSSAO.x
name	= "SvSSAO.x"
remark	= "SvSSAOの紹介動画が見つからないので他のエフェクトの紹介動画sm15369179で代用"
creator	= "そぼろ"
nico	= "sm15369179"
page	= "[MMD/Effects](https://onedrive.live.com/?id=EF581C37A4524EDA%21108&cid=EF581C37A4524EDA)"

[[item]]
id	 	= "5.0006"	# KiraKira_Z_LE 改変 sakura
name	= "KiraKira_Z_LE<br>改変 sakura"
remark	= "-"
creator	= "さくや"
nico	= "-"
page	= "bowlroll/100747"

[[item]]
id	 	= "5.0007"	# 被写界深度
name	= "被写界深度"
remark	= "-"
creator	= "矢立峠"
nico	= "sm36653860"
page	= "bowlroll/221627"

[[item]]
id	 	= "5.0008"	# CheapLens.x
name	= "CheapLens.x"
remark	= "-"
creator	= "そぼろ"
nico	= "sm15369179"
page	= "[MMD/Effects](https://onedrive.live.com/?id=EF581C37A4524EDA%21108&cid=EF581C37A4524EDA)"

[[item]]
id	 	= "5.0009"	# WorkingFloorX
name	= "WorkingFloorX.x"
remark	= ""
creator	= "針金P"
nico	= "im1575145"
page	= "[針金のブログ](https://hariganep.seesaa.net/article/201203article_1.html)"

[[item]]
id	 	= "5.0010"	# AutoLuminous4
name	= "AutoLuminous4"
remark	= "-"
creator	= "そぼろ"
nico	= "sm16087751"
page	= "[MMD/Effects](https://onedrive.live.com/?id=EF581C37A4524EDA%21108&cid=EF581C37A4524EDA)"

# 6.xxxx = 衣装 ########################

[[item]]
id	 	= "6.0001"	# ヨガウェアー
name	= "ヨガウェアー"
remark	= "-"
creator	= "Tovie"
nico	= "-"
page	= "booth/tovie/5844504"

# 7.xxxx = ポーズ ######################

[[item]]
id	 	= "7.0001"	# 普通の撮影ポーズ2
name	= "普通の撮影ポーズ2"
remark	= "-"
creator	= "KEITEL"
nico	= "im5536377"
page	= "bowlroll/93163"

#############################################
# A.xxxx = 楽曲
# B.xxxx = 振付
# C.xxxx = モーション
# D.xxxx = リップ
# E.xxxx = 表情
# F.xxxx = リップ表情
# G.xxxx = カメラ

# 楽曲 唱 ###################################

[[item]]
id	 	= "A.0001"	# 楽曲 唱
name	= "唱"
remark	= "-"
creator	= "作曲：Giga / TeddyLoid<br>作詞：トップハムハット狂<br>歌唱：Ado"
nico	= "sm42896186"
page	= "-"

[[item]]
id	 	= "B.0001"	# 振付 唱
name	= "唱"
remark	= "-"
creator	= "ぽるし"
nico	= "sm42828338"
page	= "-"

[[item]]
id	 	= "C.0001"	# モーション 唱
name	= "唱"
remark	= "-"
creator	= "づなうじ"
nico	= "sm43896215"
page	= "bowlroll/321725"

[[item]]
id	 	= "F.0001"	# リップ表情 唱
name	= "唱"
remark	= "-"
creator	= "ノン"
nico	= "im9231038"
page	= "モーションに同梱"

[[item]]
id	 	= "G.0001"	# カメラ 唱
name	= "唱"
remark	= "-"
creator	= "木村まこと"
nico	= "sm43918621"
page	= "bowlroll/322359"

# 楽曲 ハローセカイ #########################

[[item]]
id	 	= "A.0002"	# 楽曲 ハローセカイ
name	= "ハローセカイ"
remark	= "-"
creator	= "DECO*27"
nico	= "sm44594615"
page	= "-"

[[item]]
id	 	= "B.0002"	# 振付 ハローセカイ
name	= "ハローセカイ"
remark	= "-"
creator	= "おもち"
nico	= "sm44732070"
page	= "-"

[[item]]
id	 	= "C.0002"	# モーション ハローセカイ
name	= "ハローセカイ"
remark	= "-"
creator	= "づなうじ"
nico	= "sm44903242"
page	= "bowlroll/321725"

[[item]]
id	 	= "F.0002"	# リップ表情 ハローセカイ
name	= "ハローセカイ"
remark	= "-"
creator	= "ノン"
nico	= "im9231038"
page	= "モーションに同梱"

[[item]]
id	 	= "G.0002"	# カメラ ハローセカイ
name	= "ハローセカイ"
remark	= "-"
creator	= "yuima"
nico	= "sm44908561"
page	= "bowlroll/335048"

# 楽曲 Din Don Dan ##########################

[[item]]
id	 	= "A.0003"	# 楽曲 Din Don Dan
name	= "Din Don Dan"
remark	= "-"
creator	= "Mayumi Morinaga"
nico	= "-"
page	= "youtube/9BEzsuUuedA"

[[item]]
id	 	= "B.0003"	# 振付 Din Don Dan
name	= "Din Don Dan"
remark	= "-"
creator	= "Dai."
nico	= "-"
page	= "x.com/auridy/674527442426572800"

[[item]]
id	 	= "C.0003"	# モーション Din Don Dan
name	= "Din Don Dan"
remark	= "-"
creator	= "ぴよ"
nico	= "sm31003897"
page	= "bowlroll/133412"

[[item]]
id	 	= "G.0003"	# カメラ Din Don Dan
name	= "Din Don Dan"
remark	= "-"
creator	= "NOMBIRI-YA"
nico	= "sm32749550"
page	= "[NOMBIRI-YA](https://ux.getuploader.com/nombiriya/download/12/二人用DinDonDanカメラ+おまけ.zip)"

# 楽曲 よくばり ###################################

[[item]]
id	 	= "A.0004"	# 楽曲 よくばり
name	= "よくばり"
remark	= "-"
creator	= "Ayase"
nico	= "sm37073901"
page	= "-"

[[item]]
id	 	= "B.0004"	# 振付 よくばり
name	= "よくばり"
remark	= "-"
creator	= "神沢有紗"
nico	= "sm37130304"
page	= "-"

[[item]]
id	 	= "C.0004"	# モーション よくばり
name	= "よくばり"
remark	= "-"
creator	= "づなうじ"
nico	= "sm37478923"
page	= "bowlroll/235498"

[[item]]
id	 	= "G.0004"	# カメラ よくばり
name	= "よくばり"
remark	= "-"
creator	= "ノン"
nico	= "sm37486571"
page	= "bowlroll/235607"

# 楽曲 回生 ###################################

[[item]]
id	 	= "A.0005"	# 楽曲 回生
name	= "回生"
remark	= "-"
creator	= "ゆくえわっと"
nico	= "sm38151837"
page	= "-"

[[item]]
id	 	= "B.0005"	# 振付 回生
name	= "回生"
remark	= "-"
creator	= "足太ぺんた"
nico	= "sm38348434"
page	= "-"

[[item]]
id	 	= "C.0005"	# モーション 回生
name	= "回生"
remark	= "-"
creator	= "ない"
nico	= "sm40151366"
page	= "bowlroll/273400"

[[item]]
id	 	= "G.0005"	# カメラ 回生
name	= "回生"
remark	= "-"
creator	= "まさちち"
nico	= "sm40179415"
page	= "bowlroll/273748"

# 楽曲 Lamb. ##################################

[[item]]
id	 	= "A.0006"	# 楽曲 Lamb.
name	= "Lamb."
remark	= "-"
creator	= "GARNiDELiA"
nico	= "sm22012252"
page	= "-"

[[item]]
id	 	= "B.0006"	# 振付 Lamb.
name	= "Lamb."
remark	= "-"
creator	= "みうめ"
nico	= "sm22013530"
page	= "本家振付"

[[item]]
id	 	= "B.0007"	# 振付 Lamb. その2
name	= "Lamb."
remark	= "冒頭部分がモーション C.0006 の参考にされた"
creator	= "Az"
nico	= "sm22352756"
page	= "冒頭部アレンジ"

[[item]]
id	 	= "C.0006"	# モーション Lamb.
name	= "Lamb."
remark	= "-"
creator	= "yurie"
nico	= "sm22498017"
page	= "bowlroll/30717"

[[item]]
id	 	= "G.0006"	# カメラ Lamb.
name	= "Lamb."
remark	= "-"
creator	= "Amelio"
nico	= "sm22746359"
page	= "bowlroll/31598"

# 楽曲 少女未遂 #########################

[[item]]
id	 	= "A.0009"	# 楽曲 少女未遂
name	= "少女未遂"
remark	= "-"
creator	= "古墳P"
nico	= "sm13547749"
page	= "-"

[[item]]
id	 	= "B.0009"	# 振付 少女未遂
name	= "少女未遂"
remark	= "-"
creator	= "のら<br>＠ちーちゃん"
nico	= "sm17710277"
page	= "-"

[[item]]
id	 	= "C.0009"	# モーション 少女未遂
name	= "少女未遂"
remark	= "-"
creator	= "ごしかん"
nico	= "sm18513131"
page	= "[ごっしかん](https://ux.getuploader.com/gosikan/)"

[[item]]
id	 	= "G.0009"	# カメラ 少女未遂
name	= "少女未遂"
remark	= "-"
creator	= "doramata"
nico	= "sm19290621"
page	= "bowlroll/10375"


# 楽曲 ザムザ #########################

[[item]]
id	 	= "A.0010"	# 楽曲 ザムザ
name	= "ザムザ"
remark	= "-"
creator	= "てにをは"
nico	= "sm42047041"
page	= "-"

[[item]]
id	 	= "B.0010"	# 振付 ザムザ
name	= "ザムザ"
remark	= "-"
creator	= "ひかる"
nico	= "sm43318585"
page	= "[本人の踊ってみた](https://nico.ms/sm43453626)"

[[item]]
id	 	= "C.0010"	# モーション ザムザ
name	= "ザムザ"
remark	= "-"
creator	= "mobiusP"
nico	= "sm43034568"
page	= "bowlroll/309776"

[[item]]
id	 	= "G.0010"	# カメラ ザムザ
name	= "ザムザ"
remark	= "-"
creator	= "水瀬ミナ"
nico	= "sm43039607"
page	= "bowlroll/309833"


# uses 86 #############################

[[uses]]
product = 86
ids = [
	"1.0009",	# 衣川光莉（おねーちゃん5号）
	"2.0008",	# Kawaiiルーム
	"5.0001",	# AdultShader.fx
	"5.0007",	# 被写界深度
	"A.0010",	# 楽曲 ザムザ
	"B.0010",	# 振付 ザムザ
	"C.0010",	# モーション ザムザ
	"G.0010",	# カメラ ザムザ
]

# uses 33 ##############################

[[uses]]
product = 33
ids = [
	"1.0003",	# VRoid A子
	"2.0004",	# ウェスタンステージ
	"5.0007",	# 被写界深度
	"5.0008",	# CheapLens.x
	"A.0004",	# 楽曲 よくばり
	"B.0004",	# 振付 よくばり
	"C.0004",	# モーション よくばり
	"G.0004",	# カメラ よくばり
#	"T.0001",	# VRoid Studio
#	"T.0004",	# VRM2PMXConverter
#	"T.0003",	# PmxTailor
]

# uses 37 ##############################

[[uses]]
product = 37
ids = [
	"1.0003",	# VRoid A子
	"2.0005",	# ケロリン町2.0
	"3.0002",	# 天球Sunrise001
	"5.0001",	# AdultShader.fx
	"5.0009",	# WorkingFloorX
	"A.0005",	# 楽曲 回生
	"B.0005",	# 振付 回生
	"C.0005",	# モーション 回生
	"G.0005",	# カメラ 回生
#	"T.0001",	# VRoid Studio
#	"T.0002",	# Vroid2Pmx
#	"T.0003",	# PmxTailor
]

# uses 69 ##############################

[[uses]]
product = 69
ids = [
	"1.0007",	# VRoid D子
	"2.0006",	# レンガ壁の部屋-01
	"5.0010",	# AutoLuminous4
	"5.0001",	# AdultShader.fx
	"5.0009",	# WorkingFloorX
	"A.0006",	# 楽曲 Lamb.
	"B.0006",	# 振付 Lamb.
	"B.0007",	# 振付 Lamb. その2
	"C.0006",	# モーション Lamb.
	"G.0006",	# カメラ Lamb.
]

# uses 102 #############################

[[uses]]
product = 102
ids = [
	"1.0003",	# VRoid A子
	"1.0004",	# FRoid F子
	"6.0001",	# ヨガウェアー
	"2.0003",	# ストーンヘンジ
	"3.0001",	# 桜の公園 NN8
	"5.0001",	# AdultShader.fx
	"5.0005",	# SvSSAO.x
	"5.0004",	# KiraKira_Z
	"5.0006",	# KiraKira_Z_LE 改変 sakura
	"A.0003",	# 楽曲 Din Don Dan
	"B.0003",	# 振付 Din Don Dan
	"C.0003",	# モーション Din Don Dan
	"G.0003",	# カメラ Din Don Dan
]

# uses 103 #############################

[[uses]]
product = 103
ids = [
	"1.0002",	# うに式 試1.66
	"2.0002",	# ムムム草原
	"4.0002",	# ふかふか草むら
	"5.0001",	# AdultShader.fx
	"5.0003",	# Color.fx
	"5.0002",	# o_full-AlphaTest.fx
	"A.0002",	# 楽曲 ハローセカイ
	"B.0002",	# 振付 ハローセカイ
	"C.0002",	# モーション ハローセカイ
	"F.0002",	# リップ表情 ハローセカイ
	"G.0002",	# カメラ ハローセカイ
]

# uses 104 #############################

[[uses]]
product = 104
ids = [
	"1.0001",	# ふっこ
	"2.0001",	# 絵画の洋館 廃墟版
	"4.0001",	# コウモリパーティクル
	"5.0001",	# AdultShader.fx
	"5.0005",	# SvSSAO.x
	"A.0001",	# 楽曲 唱
	"B.0001",	# 振付 唱
	"C.0001",	# モーション 唱
	"F.0001",	# リップ表情 唱
	"G.0001",	# カメラ 唱
]

# uses 107 #############################

[[uses]]
product = 107
ids = [
	"2.0007",	# 撮影用背景ステージ
	"7.0001",	# 普通の撮影ポーズ2
]

# uses 106 #############################

[[uses]]
product = 106
ids = [
	"T.0007",	# MikuMikuDance
	"T.0008",	# MikuMikuEffect
	"T.0006",	# Ut Video Codec
	"T.0010",	# つんでれんこ
	"T.0009",	# AviUtl
	"T.0011",	# PMXエディター
	"P.0001",	# 準標準ボーン追加
	"P.0002",	# 闇鍋プラグイン
	"P.0003",	# 捩りボーン自動分散
	"T.0001",	# VRoid Studio
	"T.0004",	# VRM2PMXConverter
	"T.0002",	# Vroid2Pmx
	"T.0003",	# PmxTailor
	"T.0012",	# VMDサイジング
	"T.0014",	# movie2avi.bat
	"T.0015",	# PictAcc
	"T.0013",	# COEIROINK
	"T.0005",	# BowlRoll
]

# uses 110 #############################

[[uses]]
product = 110
ids = [
	"1.0006",	# VRoid C子
	"1.0007",	# VRoid D子
	"5.0001",	# AdultShader.fx
	"A.0009",	# 楽曲 少女未遂
	"B.0009",	# 振付 少女未遂
	"C.0009",	# モーション 少女未遂
]

